/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppEditor: typeof import('./src/components/AppEditor.vue')['default']
    AppUpload: typeof import('./src/components/AppUpload.vue')['default']
  }
}
